Repository IBM/data-broker, pull requests merged in 2019-11, with the labels that each got.

#95 Iterator feature
  backend/common/dbbe_api.h
  backend/redis/complete.c
  backend/redis/create.c
  backend/redis/iterator.h
  backend/redis/parse.c
  backend/redis/parse.h
  backend/redis/protocol.c
  backend/redis/receiver.c
  backend/redis/redis.c
  backend/redis/redis.h
  backend/redis/redis_cmds.h
  backend/redis/request.h
  backend/redis/sender.c
  backend/redis/test/backend_redis_create_test.c
  bindings/C/CMakeLists.txt
  bindings/C/src/dbrIterator.c
  include/errorcodes.h
  include/libdatabroker.h
  src/CMakeLists.txt
  src/api/dbrDetach.c
  src/api/dbrIterator.c
  src/lib/completion.c
  src/lib/request.c
  src/libdbrAPI.h
  test/CMakeLists.txt
  test/test_dbrIterator.c
  test/test_errorcodes.c
Labels: feature, severity 2

#97 add a function to add key to iterator cache; return EOF as last key
  backend/redis/iterator.h
  backend/redis/parse.c
  test/test_dbrIterator.c
Labels: feature, refactor, severity 2

#96 python binding updated with iterator
  bindings/python/dbr_module/dbr.py
  bindings/python/dbr_module/dbr_errorcodes.py
  bindings/python/dbr_module/dbr_interface.py
  bindings/python/dbr_module/errorcodes.py
  bindings/python/examples/dbr_iterate.py
  bindings/python/setup.py.in
Labels: feature

#98 fix some minor compiler complaints
  backend/redis/parse.c
  test/test_dbrIterator.c
Labels: bug

#101 updated documentation and version numbers
  .github/CODEOWNERS
  Changelog
  README.md
  bindings/python/README.md
  bindings/python/setup.py.in
  doc/conf.tex
  doc/guide.tex
  include/libdatabroker.h
Labels: refactor

#102 a few minor fixes and code improvements
  backend/redis/create.c
  backend/redis/iterator.h
  backend/redis/namespace.c
  backend/redis/parse.c
  backend/redis/receiver.c
  backend/redis/redis.c
  backend/redis/sender.c
  backend/redis/test/backend_redis_namespace_test.c
  backend/redis/test/backend_redis_parse_test.c
  backend/redis/test/backend_redis_test.c
  backend/transports/smallcopy.c
  src/lib/completion.c
  test/test_dbrIterator.c
Labels: refactor, severity 3

#103 use this PR to solve current mac-build issues and prepare a new tagged version
  backend/redis/iterator.h
  backend/redis/namespace.c
  backend/redis/parse.c
  backend/redis/test/backend_redis_namespace_test.c
  backend/redis/test/backend_redis_parse_test.c
  doc/guide.tex
  src/lib/namespace.c
  src/util/memutil.h
  test/test_dbrIterator.c
  test/test_dbrPutGet.c
  test/test_dbrReMove.c
  test/test_utils.h
Labels: bug, severity 3

#104 allow to disable Redis authentication by setting DBR_AUTHFILE=NONE
  Changelog
  backend/redis/connection.c
Labels: feature

#105 improved error reporting for connections to Redis
  backend/redis/connection.c
  backend/redis/redis.c
Labels: feature, severity 3

#106 backend command specification
  backend/common/completion.h
  backend/common/dbbe_api.h
  backend/redis/complete.c
  backend/redis/complete.h
  backend/redis/parse.c
  backend/redis/receiver.c
  backend/redis/redis.c
  backend/redis/sender.c
  backend/redis/test/CMakeLists.txt
  backend/redis/test/backend_redis_completion_test.c
  backend/redis/test/backend_redis_resp_parse_test.c
  backend/transports/smallcopy.c
  src/api/dbrAttach.c
  src/lib/completion.c
Labels: refactor, severity 3

#107 fix send-cmd function for large transfers that exceed limit of single sendmsg call
  backend/redis/connection.c
  backend/redis/connection.h
Labels: bug, severity 2
