Repository IBM/data-broker, pull requests merged in 2019-02, with the labels that each got.

#43 Connection recovery feature
  backend/redis/conn_mgr.c
  backend/redis/conn_mgr.h
  backend/redis/connection.c
  backend/redis/connection.h
  backend/redis/locator.c
  backend/redis/locator.h
  backend/redis/receiver.c
  backend/redis/redis.c
  backend/redis/sender.c
  backend/redis/slot_bitmap.h
  backend/redis/test/CMakeLists.txt
  backend/redis/test/backend_redis_conn_mgr_test.c
  backend/redis/test/backend_redis_locator_test.c
  backend/redis/test/backend_redis_resp_parse_test.c
  backend/redis/test/backend_redis_slot_bitmap_test.c
Labels: feature, severity 2

#44 properly implemented get/read for redis back-end
  backend/common/dbbe_api.h
  backend/redis/parse.c
  backend/redis/receiver.c
  src/api/dbrGet.c
  src/api/dbrRead.c
  src/lib/completion.c
  test/test_dbrPutGetA.c
Labels: bug, feature, severity 2

#45 initial remove-cmd feature
  backend/redis/create.c
  backend/redis/parse.c
  backend/redis/parse.h
  backend/redis/protocol.c
  backend/redis/receiver.c
  backend/redis/redis_cmds.h
  test/test_dbrPutGet.c
Labels: feature, severity 2

#47 Initial implementation of move cmd for Redis backend
  backend/redis/connection.c
  backend/redis/create.c
  backend/redis/parse.c
  backend/redis/parse.h
  backend/redis/protocol.c
  backend/redis/protocol.h
  backend/redis/receiver.c
  backend/redis/redis.c
  backend/redis/redis_cmds.h
  backend/redis/request.h
  backend/redis/sender.c
  backend/redis/test/backend_redis_create_test.c
  backend/redis/test/backend_redis_resp_parse_test.c
  backend/redis/test/backend_redis_test.c
  src/lib/completion.c
  src/lib/request.c
  test/CMakeLists.txt
  test/test_dbrReMove.c
Labels: feature, severity 2

#48 Feature/move error case handling
  backend/redis/parse.c
  src/api/dbrMove.c
  src/lib/completion.c
  test/test_dbrReMove.c
Labels: feature, severity 2

#49 Several fixes discovered by compilers
  CMakeLists.txt
  backend/redis/connection.c
  backend/redis/create.c
  backend/redis/parse.c
  backend/redis/receiver.c
  backend/redis/redis.c
  backend/redis/redis_cmds.h
  backend/redis/refcounter.h
  backend/redis/test/backend_redis_crc16_test.c
  backend/redis/test/backend_redis_resp_parse_test.c
  include/errorcodes.h
  src/test/test_request.c
  test/test_delete_scan.c
  test/test_utils.h
Labels: bug, severity 2

#50 feature/remove add missing test cases
  backend/redis/test/backend_redis_create_test.c
  backend/redis/test/backend_redis_resp_parse_test.c
  backend/redis/test/backend_redis_test.c
Labels: feature, severity 2

#51 Py3fix
  bindings/python/CMakeLists.txt
  bindings/python/build.sh
  bindings/python/dbr_module/dbr.py
  bindings/python/dbr_module/dbr_errorcodes.py
  bindings/python/dbr_module/dbr_interface.py
  bindings/python/dbr_module/errorcodes.py
  bindings/python/examples/dbr_attach.py
  bindings/python/examples/dbr_create.py
  bindings/python/examples/dbr_directory.py
  bindings/python/examples/dbr_numpy.py
  bindings/python/examples/dbr_putget.py
  bindings/python/examples/dbr_putgetA.py
  bindings/python/requirements.txt
  bindings/python/setup.py.in
  bindings/python/test/dbr_directory.py
  bindings/python/test/dbr_putget.py
  bindings/python/test/dbr_putgetA.py
Labels: feature

#52 Refactoring of redis command creation
  backend/redis/create.c
  backend/redis/protocol.c
  backend/redis/protocol.h
  backend/redis/redis_cmds.h
Labels: refactor, severity 2

#53 Feature/refcnt delete
  backend/redis/create.c
  backend/redis/parse.c
  backend/redis/parse.h
  backend/redis/protocol.c
  backend/redis/protocol.h
  backend/redis/receiver.c
  backend/redis/redis_cmds.h
  backend/redis/refcounter.h
  backend/redis/request.c
  backend/redis/request.h
  backend/redis/test/backend_redis_create_test.c
  backend/redis/test/backend_redis_resp_parse_test.c
  backend/redis/test/backend_redis_test.c
  src/api/dbrDelete.c
  src/api/dbrDetach.c
  src/lib/namespace.c
Labels: feature, severity 2

#55 Feature/refcnt delete updates and fixes
  Changelog
  backend/redis/complete.c
  backend/redis/create.c
  backend/redis/parse.c
  backend/redis/protocol.c
  backend/redis/protocol.h
  backend/redis/receiver.c
  backend/redis/redis_cmds.h
  backend/redis/request.c
  backend/redis/request.h
  backend/redis/s2r_queue.c
  backend/redis/test/backend_redis_create_test.c
  backend/redis/test/backend_redis_resp_parse_test.c
  bindings/C/src/dbrCreate.c
  src/api/dbrCreate.c
  src/api/dbrDelete.c
  src/lib/completion.c
  test/test_dbrAttach.c
  test/test_dbrCreate.c
Labels: bug, feature, severity 2
